### PR TITLE
Fix eigen3 cmake

### PR DESCRIPTION
**Pull request by victorv**
eigen3 uses pkg_config rather than a module to find eigen3.

### CODE REVIEW

**Comment by beniz** [comment]
Thank you. The PR doesn't work for me on raw 14.04 nor on 16.04, the error is as follows:

```
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for one of the modules 'eigen3'
CMake Error at CMakeLists.txt:53 (include_directories):
  include_directories given empty-string as include directory.


CMake Error at CMakeLists.txt:54 (include_directories):
  include_directories given empty-string as include directory.
```

This is due to the line

```
include_directories("${EIGEN3_INCLUDE_DIR}")
```

Also, you are calling on `include_directories` twice.

**Comment by victorv** [comment]
Yes - those lines are not needed.

**Comment by victorv** [comment]
Let's hold off on the PR as there is an unrelated problem with libcurl stopping me from building this cleanly.

**Comment by beniz** [comment]
`libcurl` mayhem is due to Ubuntu still shipping a wrongly built version AFAIK, the solution lies here: https://github.com/beniz/deepdetect/issues/126#issuecomment-284534843

**Comment by victorv** [comment]
Yes - I have a cleaner solution I am testing now.

**Comment by victorv** [comment]
@beniz - you must have used g++-4.9 as the default g++ on 14.04 is 4.8 which has the following error

> NVCC src/caffe/layers/detection_output_layer.cu
./include/caffe/filler.hpp(288): warning: statement is unreachable
>
>/usr/include/boost/property_tree/detail/json_parser_read.hpp: In constructor ‘boost::property_tree::json_parser::json_grammar<Ptree>::definition<Scanner>::definition(const boost::property_tree::json_parser::json_grammar<Ptree>&)’:
>/usr/include/boost/property_tree/detail/json_parser_read.hpp:257:264: error: ‘type name’ declared as function returning an array
                escape
>/usr/include/boost/property_tree/detail/json_parser_read.hpp:257:264: error: ‘type name’ declared as function returning an array
>make[3]: *** [.build_release/cuda/src/caffe/layers/detection_output_layer.o] Error 1

**Comment by victorv** [comment]
Looks like updating the installation instructions to include g++-4.9 will make a vanilla install possible with the latest update to the PR still on my machine.

Looks like the build assumes tensorflow is installed? and it uses the eigen from that repo rather than the default eigen3 installed in /usr/include which is not included by default in the caffe Makefile.config pathing.

> sudo add-apt-repository ppa:ubuntu-toolchain-r/test
> sudo apt-get update
> sudo apt-get install g++-4.9

**Comment by victorv** [comment]
Latest PR includes fix for default eigen install path at /usr/include/eigen3. It now builds clean on 14.04.5 with the required apt-get installs noted on the website plus the ones noted above.

**Comment by victorv** [comment]
Looks like a core dump

DeepDetect [ commit ad708308675cada8b1ea5ef62f6dbaabe6535668 ]

INFO - 18:15:06 - Running DeepDetect HTTP server on localhost:8080

ERROR - 18:15:06 - Error binding to socket.
terminate called without an active exception
Aborted (core dumped)

**Comment by victorv** [comment]
I was running something else on port 8080 and the core dump was a result of the collision - all is good now.

**Comment by victorv** [comment]
I should make a separate PR to handle port collisions.

**Comment by beniz** [comment]
Thanks. We have a policy to stick to the default packages of distributions we support professionally (14.04 & 16.04). For this reason we won't require a compiler change. 

I believe the error you are experiencing with `nvcc` comes from using Cuda 8 along with Ubuntu 14.04 and default compiler. This is something we should definitely add to README and FAQ. Another reason we'll stick to default compilers is that this is an NVidia issue with proprietary software that only affects a minority of users (GPU builds + Cuda8 + Ubuntu 14.04). If you'd like to use Cuda8, I recommend switching to 16.04 anyways. Please update the PR accordingly. You can maintain a side PR that forces gcc-4.9 and we'd be happy to point users to it (though it won't be merged).

Regarding the eigen3 situation, please make sure that the tensorflow build passes as well. If you are not sure how to do this, please cleanup the PR from the compiler changes and we'll run the checks.

I know how frustrating these rules can be, but they are hundreds of builds and hosted DD services out there and we need to be careful with changes. Admittedly our 'policies' are not written and this is something we should do eventually.

**Comment by victorv** [comment]
Thanks for the feedback. Sticking to default compilers makes sense. I will find a solution which avoids changing the compiler.

**Comment by victorv** [comment]
I used the defaults for tensorflow - there are some patches applied which I am not sure about 

> HEAD is now at e895d5c... Fixing 2 minor issues as suggested by Gunan.
checking file tensorflow/BUILD
Unreversed patch detected!  Ignore -R? [n] 
Apply anyway? [n] 
Skipping patch.
3 out of 3 hunks ignored
patching file tensorflow/BUILD
Hunk #1 succeeded at 242 (offset 36 lines).
Hunk #2 succeeded at 252 (offset 36 lines).
Hunk #3 succeeded at 263 (offset 36 lines).
checking file tensorflow/python/BUILD
Hunk #1 succeeded at 2413 (offset 572 lines).
Please specify the location of python. [Default is /usr/bin/python]: 
Please specify optimization flags to use during compilation [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? (Linux only) [Y/n] 
jemalloc enabled on Linux
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]
Using python library path: /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] 
No CUDA support will be enabled for TensorFlow
Configuration finished

**Comment by beniz** [comment]
It's fine to apply the patches, even if some may fail after some TF updates. You may want to say no to `jemalloc` since we're already using tcmalloc and this may conflict.

**Comment by victorv** [comment]
built using `cmake -DUSE_TF=1 -DHAVE_CUDNN=1 ..` and no to jemalloc and yes to CUDA

INFO: From Executing genrule //tensorflow/cc:array_ops_genrule:
W tensorflow/core/framework/op_gen_lib.cc:194] Squeeze can't find input squeeze_dims to rename
INFO: Elapsed time: 2172.903s, Critical Path: 1679.04s
.................
Google Mock not present.  Fetching gmock-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129    0   129    0     0    379      0 --:--:-- --:--:-- --:--:--   380
100  362k  100  362k    0     0   337k      0  0:00:01  0:00:01 --:--:--  884k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129    0   129    0     0    397      0 --:--:-- --:--:-- --:--:--   398
100  618k  100  618k    0     0   640k      0 --:--:-- --:--:-- --:--:-- 1421k
+ autoreconf -f -i -Wall,no-obsolete
./autogen.sh: 48: ./autogen.sh: autoreconf: not found
make[2]: *** [tensorflow/src/tensorflow-stamp/tensorflow-configure] Error 127
make[1]: *** [CMakeFiles/tensorflow.dir/all] Error 2
make: *** [all] Error 2

**Pull request closed without merging**
