### PR TITLE
Support for unsupervised models + access to inner Caffe neural net's layers

### PR DESCRIPTION
**Pull request by beniz**
This PR considers the ability to extract the value of inner layers from deep neural nets using the underlying Caffe (#56). It is observed that returning the layer array of values can be considered similar to the output of an unsupervised model. Therefore the PR takes advantage of this by building the support for unsupervised models, that had been on the roadmap anyways.

Example with Googlenet, same setting as http://www.deepdetect.com/tutorials/imagenet-classifier/ :
- `unsupervised` service creation:
```
curl -X PUT "http://localhost:8080/services/imgserv" -d "{\"mllib\":\"caffe\",\"description\":\"image classification\",\"type\":\"unsupervised\",\"parameters\":{\"input\":{\"connector\":\"image\",\"height\":224,\"width\":224},\"mllib\":{\"nclasses\":304}},\"model\":{\"repository\":\"/path/to/model/\"}}"
```
Note that the service's `type` is `unsupervised`.

- requesting net's layer `pool5/7x7_s1`:
```
curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"imgserv\",\"parameters\":{\"mllib\":{\"extract_layer\":\"pool5/7x7_s1\"}},\"data\":[\"https://i.ytimg.com/vi/4sMQ9dEpuo8/maxresdefault.jpg\",\"https://i.ytimg.com/vi/4sMQ9dEpuo8/maxresdefault.jpg\"]}"
```
 Note the `extract_layer` parameter to the `mllib` object.

- response:
```
{"status":{"code":200,"msg":"OK"},"head":{"method":"/predict","time":2695.0,"service":"imgserv"},"body":{"predictions":{"last":true,"vals":[0.0,0.16237296164035798,0.0,2.24597430229187,0.5692943334579468,...,1.8091919422149659,0.0],"uri":"https://i.ytimg.com/vi/4sMQ9dEpuo8/maxresdefault.jpg"}}}
```

You can similarly try to get layer `loss3/classifier`, which is the one the layers used in [Pinterest search](http://arxiv.org/abs/1505.07647) among others.

Note:
- by design, dd requires a service to be either `supervised` or `unsupervised`: this means that to extract a net's layer, the service **must** be created as `unsupervised` and the supervised metrics are not available
- there's no difficulty in supporting multiple layer extractions at once, we may add it as needed
- binarized output of the extracted value is not part of this PR (yet)

### CODE REVIEW

**Comment by masakinakada** [comment]
Hi Em,

Thank you so much for this update. You are my life saver. I was trying to modify other part of the code but was a bit struggling.

I will try to complete it with your awesome update! 
Thank you very much. I will give you update on my progress.

**Comment by masakinakada** [comment]
Hi Em,

I got the following error when I was building this brach. 
Could you help me to solve it? 
Thank you very much for your kind supports!

In file included from /home/ubuntu/deepdetect/src/services.h:31:0,
                 from /home/ubuntu/deepdetect/src/apistrategy.h:26,
                 from /home/ubuntu/deepdetect/src/deepdetect.h:25,
                 from /home/ubuntu/deepdetect/src/deepdetect.cc:22:
/home/ubuntu/deepdetect/src/outputconnectorstrategy.h:113:41: fatal error: unsupervisedoutputconnector.h: No such file or directory
 #include "unsupervisedoutputconnector.h"
                                         ^
compilation terminated.
make[2]: *** [src/CMakeFiles/ddetect.dir/deepdetect.cc.o] Error 1
make[1]: *** [src/CMakeFiles/ddetect.dir/all] Error 2
make: *** [all] Error 2

**Comment by beniz** [comment]
@masakinakada oops, my bad, should be fixed now.

**Comment by masakinakada** [comment]
This version works perfect! I could successful get the predict API and get the inner layer output. 
Thank you so much Em.

**Comment by beniz** [comment]
OK great, please share the next steps in the image search issue, I'm interested in playing a bit with similarity search myself.

**Comment by masakinakada** [comment]
Yes, I will do so! I have a business trip starting from tonight but will
work on it next week!
Thanks a lot Em!

On Fri, Feb 5, 2016 at 12:12 PM, Emmanuel Benazera <notifications@github.com

**Pull request merged**
