### PR TITLE
Imgdetect demo

### PR DESCRIPTION
**Pull request by alx**
Static html interface to visualize results from image classifier predict api.

### CODE REVIEW

**Comment by alx** [comment]
replace vendor dependencies with bower

**Comment by beniz** [comment]
If I understand correctly, this requires bower installation, which is not packaged with the reference distro Ubuntu 14.04. Is there any other way to let the browser get the required bootstrap file online automatically ?

**Comment by alx** [comment]
Replaced bower by cdnjs links.

**Comment by beniz** [comment]
Many thanks. However, this does not work as is: the DeepDetect server complains with 
```
ERROR - Unknown Service=api
```
I guess this is due to passing the /api to the DeepDetect server. Any idea ?

**Comment by beniz** [comment]
OK, it's `/api` in the rewrite rule instead of `locationapi`.

**Comment by beniz** [comment]
Now, there's a bug in the demo:
- classify one image
- classify another image
-> the tags from both images are shown instead of only the predicted tags of the last image

**Comment by alx** [comment]
You need to use the nginx rules as specified in the readme to have
deepdetect server behind a proxy on the same host/port as the webpage.

**Pull request merged**
