### PR TITLE
making client API compatible with python3

### PR DESCRIPTION
**Pull request by kyrs**
Hi beniz,
I have created the client Api code compatible with python3 and python2 both. Have a look at it.

### CODE REVIEW

**Comment by beniz** [comment]
Thanks for the PR @kyrs this is well done!

I've played with it a bit and here are my suggested changes:

- replace `hack_decode(js)` with `js.decode('utf-8')` since this is what is recommended with Python3, see http://stackoverflow.com/questions/6862770/python-3-let-json-object-accept-bytes-or-let-urlopen-output-strings
- remove the whole `hack_decode` function
- remove the `from builtins import str as text`

Could you fix the points above and commit the changes please ? (Btw, this helped me finding a big bug in the dd_client file, which I'll fix after your changes are being merged).

Thanks again!

**Comment by kyrs** [comment]
@beniz  I have made the necessary changes you have asked me to do. Is there any other changes to be done ?

**Comment by beniz** [comment]
This is perfect thank you, and it completes #63.

**Comment by beniz** [comment]
Good job and thanks for your contribution :)

**Pull request merged**
